version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./public:/code/public
    ports:
      - '80:80'
      - '443:443'

  web:
    build: .
    command: sh -c "/code/run_local.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./public:/code/public
      - ./backend:/code/backend
      - ./frontend:/code/frontend

  celery:
    build: .
    command: celery -A app worker --loglevel=info -B
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./public:/code/public
      - ./backend:/code/backend
      - ./frontend:/code/frontend

  neo4j:
    image: neo4j:5.6.0
    env_file:
      - .env
    volumes:
      - ./dumps/neo4j:/dumps
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
    ports:
      - '7474:7474'
      - '7687:7687'

  postgres:
    image: postgres:14.5-alpine
    restart: always
    env_file:
    - .env
    volumes:
      - ./dumps/postgresql:/dumps
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
     image: redis:alpine
     ports:
       - '6379:6379'
