from os import getenv, path
import re
import json
from django import template
from django.conf import settings
from django.utils.safestring import mark_safe

register = template.Library()

is_absolute_url = lambda url: re.match("^https?://", url)   # noqa

DEV = settings.DEBUG_FRONTEND
DEV_SERVER_ROOT = getenv("DEV_VITE_ROOT", "http://localhost:3001")


def vite_manifest(entries_names):
    # app_name = ''
    # manifest_filepath = path.join(app_name, 'static/manifest.json')
    # frontend/static/app/dist

    if DEV:
        scripts = [
            f"{DEV_SERVER_ROOT}/@vite/client",
        ]

        for name in entries_names:
            scripts.append(f'{DEV_SERVER_ROOT}/{name}')

        styles = []
        return scripts, styles
    else:
        manifest_filepath = path.join(settings.BASE_DIR, '..', 'frontend', 'build', 'manifest.json')
        with open(manifest_filepath) as fp:
            manifest = json.load(fp)
        _processed = set()

        def _process_entries(names):
            scripts = []
            styles = []

            for name in names:
                if name in _processed:
                    continue

                chunk = manifest[name]

                import_scripts, import_styles = _process_entries(chunk.get('imports', []))
                scripts += import_scripts
                styles += import_styles

                scripts += [chunk['file']]
                styles += [css for css in chunk.get('css', [])]
                _processed.add(name)

            absolute_url = lambda x: f'/{x}'  # noqa
            scripts = map(absolute_url, scripts)
            styles = map(absolute_url, styles)

            return scripts, styles

        return _process_entries(entries_names)


@register.simple_tag(name="vite_styles")
def vite_styles(*entries_names):
    """
    Populate an html template with styles generated by vite

    Usage::

        {% vite_styles 'main.js' 'other-entry.js' %}

    Examples::
        <head>
            ...
            {% vite_styles 'main.js' 'other-entry.js' %}
        </head>
    """
    _, styles = vite_manifest(entries_names)
    styles = map(lambda href: href if is_absolute_url(href) else href, styles)
    as_link_tag = lambda href: f'<link rel="stylesheet" href="{href}" />'  # noqa
    return mark_safe("\n".join(map(as_link_tag, styles)))


@register.simple_tag(name="vite_scripts")
def vite_scripts(*entries_names):
    """
    Populate an html template with script tags generated by vite

    Usage::

        {% vite_scripts 'main.js' 'other-entry.js' %}

    Examples::
        <body>
            <!-- Your HTML -->
            {% vite_scripts 'main.js' 'other-entry.js' %}
        </body>
    """
    scripts, _ = vite_manifest(entries_names)
    scripts = map(lambda src: src if is_absolute_url(src) else src, scripts)
    as_script_tag = lambda src: f'<script type="module" src="{src}"></script>'  # noqa
    return mark_safe("\n".join(map(as_script_tag, scripts)))
